### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by 3x071c** [aiji42/remix-esbuild-override#8]
Trying to get this to run with my Cloudflare Pages + Remix + Emotion + Chakra-UI app. After following the `README.md` guide, I'm encountering the following error:
```console
$ npm run dev
Building Remix app in development mode...
Error: Error loading Remix config in /Users/.../remix.config.js
    at Object.readConfig (/Users/.../node_modules/@remix-run/dev/config.js:67:11)
    at Object.build (/Users/.../node_modules/@remix-run/dev/cli/commands.js:151:31)
    at Object.run (/Users/.../node_modules/@remix-run/dev/cli/run.js:351:22)
    at Object.<anonymous> (/Users/.../node_modules/@remix-run/dev/cli.js:16:11)
```
First I thought this was a misconfiguration problem (or possibly an incompatibility with CF Pages), but it turns out that your `/example` runs into the same problem. I see that this package was just freshly upgraded 5 hours ago, so I'll downgrade to v1 for now. Thank you for investing your time in maintaining this publically, can't wait to have this fixed! 💯

**Comment by aiji42** [comment]
@3x071c Thanks for actually using this library.
I am wondering why I am getting errors like the one you presented, since I have verified that `/example` is running correctly, as shown in the image below.

![スクリーンショット 2022-03-28 午前9 43 23](https://user-images.githubusercontent.com/6711766/160309176-5e9548e3-0b94-4977-b30d-86dcab72ca67.png)

I would like to know in order to streamline my investigation.
- What is the version of Node in your environment?
- Downgrade `remix-esbuild-override` to v1 in your repository and get the same error?

**Comment by gnimmelf** [comment]
I can confirm same error;

node -v 
v17.8.0
npm -v
8.5.0

Both
"remix-esbuild-override": "^1.0.0",
"remix-esbuild-override": "^2.0.0",
fail with same error, so only diff is yarn vs npm?

Cheers!

**Comment by aiji42** [comment]
@gnimmelf Thanks for the detailed information. This will help me in my investigation.
I promise to address and resolve the issue as soon as possible.

**Comment by 3x071c** [comment]
@aiji42 Thanks for investigating. Perhaps this is an npm-specific issue?

**Comment by aiji42** [comment]
@3x071c I have not yet been able to determine the cause of the problem, but I believe it is likely.

**Comment by aiji42** [comment]
The remix-esbuild-override intercepts the esbuild call from remix by rewriting the path to esbuild under node_modules using the file system.
I suspect that the error is caused by a slight difference in the configuration of the directory under node_modules during module installation between yarn and npm.

**Comment by aiji42** [comment]
@3x071c @gnimmelf
Can you try to delete `node_modules/@remix-run/dev/node_modules/esbuild` and run the development command to see if it starts?
```bash
rm -rf node_modules/@remix-run/dev/node_modules/esbuild
npm run dev
```

**Comment by 3x071c** [comment]
> I would like to know in order to streamline my investigation.
> 
> - What is the version of Node in your environment?

I'm using the latest Node.js version (17.8.0), with npm

> - Downgrade `remix-esbuild-override` to v1 in your repository and get the same error?

Downgrading and reconfiguring `remix-esbuild-override` to `1.2.2` works with Remix `1.3.x`. Confusingly, it doesn't with Remix `1.2.x`.

**Comment by marcus-sa** [comment]
> node_modules/@remix-run/dev/node_modules/esbuild

Weird, that doesn't work for me.

**Comment by aiji42** [comment]
@marcus-sa Thanks for letting me know.
Is the error you observed the same as the error @3x071c presented at the beginning of the Issue?

**Comment by marcus-sa** [comment]
@aiji42 this is the error I'm currently getting 
`Cannot find module 'esbuild-org'`
`at Object.<anonymous> (/home/marcus-sa/Git/marcus-sa/onlyfans-clone/node_modules/remix-esbuild-override/dist/index.js:18:14)`

**Comment by 3x071c** [comment]
@aiji42 Works great for me! Thank you. 👍

**Comment by aiji42** [comment]
I am making this release and closing the issue. Thank you all for your help in reporting and debugging.
I am hopeful that the errors you have reported have been resolved, but if they recur, please re-open the issue.
